### PR TITLE
add --input-dice-results option

### PR DESCRIPTION
**Pull request by drebs**
Add the possibility of inputting the result of real dice throws instead of using the computer's PRNG. This is useful so you can use diceware as a word catalog, while also using other features of the program.

### CODE REVIEW

**Comment by conorsch** [comment]
@drebs Could you add a description of this PR? Based on your code, it looks like a new feature designed to accommodate dice throws, you don't have to trust your computer's RNG. I don't understand why you choose to ignore the `--num` option, though.

**Comment by drebs** [comment]
@conorsch I added the description, it is exactly what you described.

About ignoring the `--num` option, I thought it would be more practical like this and to signal the end of the throws with an empty line. At first, I thought that having to the number of words with `-n` would be too much bureaucracy, but I also understand it seems a bit weird given how the program options are organized right now. Please, don't hesitate to suggest a better approach, I'm happy to implement it. :-)

**Comment by ulif** [comment]
@drebs Thank you very much for the PR!

I see your point about offering real dice throws as an (alternative) source of randomness. I generally like the idea of alternative sources of randomness very much. Going "back to the roots" this way futhermore is really charming.

While your patch is very clean and convenient to read (thanks for that!) I am not completely happy with some details:

1. I think the patch does not use all possible terms from wordlists > 7776.  This includes the default list 
    (we use the 8k list, not the standard 7776 (=6**5) terms list). If people use longer wordlists (I, for
    instance like a filtered version of the /usr/share/dict/words list on my system, giving me about 22,000 
    words, i.e. an entropy of about 14 bits per word) they would think that they get more entropy and
    might not notice that the latter part of their wordlist is not considered at all. I think we should avoid
    this misunderstandings by all means.
2. The patch could simly break with wordlists < 7776 terms. The index computed by
    ```get_word_index_from_input()``` might result in words not existing in the wordlist used.
3. Docs for the new functionality are missing. This is not a big thing and I would be glad to add/update 
    them (the usage hints in README especially). In fact I think it is better if others explain in the docs
    what a certain developer has done/changed.
4.Tests are missing:  I'd like to keep the 100% test coverage we currently have (following the
    "untested code is broken code" convention). In this case it might become a bit tricky, as one has to
    fake raw_input in tests. I could, however, do that. Overall this is no blocker at all. Reminds me that
    we need a coverage test done by travis-CI.
5. I'd suggest to use a different char than ```-i``` for the new option as this could easily be confused 
    with any INFILE providing a wordlist. Instead I could think of letter ```-r, --randomsource``` as option
    name or something similar. This option should be usable for other sources of randomness as well.
6. Like conorsch I have a problem with the ```-n``` option being ignored. I think, instead the tool should
    ask for new dice throws as long as it takes to give N words. This behaviour would also feel more
    "natural" to me. As we have a default for ```-n``` I see not much bureaucracy in using that. On the
    contrary it feels more confusing to me to have options being ignored under certain circumstances.

All this could be handled (more or less) easily. But my main concern is: I'd love to support alternative sources of randomnes and I would not insist to be dice being the only one. Instead I think about a more common interface for any source of randomness. Think of a RaspberryPI or Arduino sampling avalanche noise or similar, for instance. To sum it up: also alternative hardware devices should be possible in my point of view.

I think, to make them work one would need to provide functions/callables that turn the output of a source of randomness into some data we can deal with uniformly. For instance something similar to the standard Python lib random functions, something like ```random.choice(seq)```. In fact that should be enough: an interface ```x``` that supports ```x.choice(wordlist)```. The ```--randomsource``` option then might support a set of keywords, say, 'dice', 'system', 'rndfile', .... with ```system``` as default.

Depending on the ```--randomsource``` option, then we could use a respective function/callable that retrieves random numbers and then allows choice() from wordlists used. The currently used ```SystemRandom``` then would be the default choice for --randomsource but could be ignored in favor of other sources like `dice`.

It might be possible to allow even plugins from other modules to provide alternative sources. But I have to check that first.

Okay, this one becomes too long.

drebs, my suggestion is: I could turn the currently used SystemRandom source into a "pluggable" source that also acts as a sample of how other sources of randomness could look like (defining an interface, etc.) and how they can be integrated into the code-source.

I think the pure source could roughly look like:

    class MySource(object):

        name = "mysource"

        def __init__(self, options):
            ...

        def choice(self, wordlist):
            """Return an element of `wordlist`.
            """
            ...

When done, you could add the, "realdice" source again, this time following the pattern of the "system" source I am going to do.

Although all the nitpicking here might sound dismissive and overcritical, I would like to stress, that I really like your idea and appreciate all your input very much. I would really love to bring that alternative sources of randomness into diceware. And having real dice as a start sounds perfect :-)

What do you think?

-- 
Uli

**Comment by andrejb** [comment]
@ulif Thanks for all the comments and the warm welcome. I'm happy to contribute the way you find best. I comment some of your comments below.

> 1 . I think the patch does not use all possible terms from wordlists > 7776. This includes the default list (we use the 8k list, not the standard 7776 (=6**5) terms list). If people use longer wordlists (I, for instance like a filtered version of the /usr/share/dict/words list on my system, giving me about 22,000 words, i.e. an entropy of about 14 bits per word) they would think that they get more entropy and might not notice that the latter part of their wordlist is not considered at all. I think we should avoid this misunderstandings by all means.

In terms of real dice throws, I think the amount of randomness would be limited either by the number of dice you throw for each word, or by the size of the wordlist, whichever amounts to the least number of indexes. Do you think that "resampling" and truncating by taking into account these two values, while also outputting a message/warning showing the randomness you're getting with a given setup, would be enough?

> 2 . The patch could simly break with wordlists < 7776 terms. The index computed by get_word_index_from_input() might result in words not existing in the wordlist used.

True. The resample-truncate approach might also solve that.

> 4 . Tests are missing: I'd like to keep the 100% test coverage we currently have (following the "untested code is broken code" convention). In this case it might become a bit tricky, as one has to fake raw_input in tests. I could, however, do that. Overall this is no blocker at all. Reminds me that we need a coverage test done by travis-CI.

I'm happy to add them once we have a clear implementation path. As an alternative approach, if you like it, you could write the tests and I could implement the code, including the pluggable source propostal. Again, let's organize the way you find best, I'm just offering to do it so you don't need to do everything, and hoping that would be less time-consuming. :-)

> 4 . I'd suggest to use a different char than -i for the new option as this could easily be confused with any INFILE providing a wordlist. Instead I could think of letter -r, --randomsource as option name or something similar. This option should be usable for other sources of randomness as well.

That is a great idea.

> 5 . Like conorsch I have a problem with the -n option being ignored. I think, instead the tool should ask for new dice throws as long as it takes to give N words. This behaviour would also feel more "natural" to me. As we have a default for -n I see not much bureaucracy in using that. On the contrary it feels more confusing to me to have options being ignored under certain circumstances.

That's fine for me. In the future, I would like to help adding something like a configuration file, so each person can save her preferences, which would be overriden by command line options. For me, for example, having spaces, non-capitalized output, and a default of 8 words would be a good set of options. How do you see the rc file idea?

> All this could be handled (more or less) easily. But my main concern is: I'd love to support alternative sources of randomnes and I would not insist to be dice being the only one. Instead I think about a more common interface for any source of randomness. Think of a RaspberryPI or Arduino sampling avalanche noise or similar, for instance. To sum it up: also alternative hardware devices should be possible in my point of view.
>
> I think, to make them work one would need to provide functions/callables that turn the output of a source of randomness into some data we can deal with uniformly. For instance something similar to the standard Python lib random functions, something like random.choice(seq). In fact that should be enough: an interface x that supports x.choice(wordlist). The --randomsource option then might support a set of keywords, say, 'dice', 'system', 'rndfile', .... with system as default.
>
> Depending on the --randomsource option, then we could use a respective function/callable that retrieves random numbers and then allows choice() from wordlists used. The currently used SystemRandom then would be the default choice for --randomsource but could be ignored in favor of other sources like dice.

That is a very good idea. It again raises the questions of amount of entropy on the source versus number of words in the wordlist, and also of configurable defaults.

> drebs, my suggestion is: I could turn the currently used SystemRandom source into a "pluggable" source that also acts as a sample of how other sources of randomness could look like (defining an interface, etc.) and how they can be integrated into the code-source.
> 
> I think the pure source could roughly look like:
>
> (...)
>
> When done, you could add the, "realdice" source again, this time following the pattern of the "system" source I am going to do.

Fantastic. If you want to split that work, I'm happy to help. Please don't hesitate to do it the way you find more economical for your workflow.

> Although all the nitpicking here might sound dismissive and overcritical, I would like to stress, that I really like your idea and appreciate all your input very much. I would really love to bring that alternative sources of randomness into diceware. And having real dice as a start sounds perfect :-)
>
> What do you think?

Thank you again. Just so you know, I also intend to package diceware for debian. I have already done it locally and I'm having the help of a friend who know a lot about packaging to fix details so I can submit it soon.

**Comment by ulif** [comment]
@andrejb: Thank you for not being pissed-off ;-)

I wlll try to be shorter now:

**Resampling**

For the "resampling": I am not sure, I understand you completely. 

Please note (this is a sidenote), that if we really use an interface which in the end only provides ```choice(wordlist)``` then this interface will not only be used for real wordlists, but also for the "special chars". I know that on the diceware.com website these special chars are treated, well, special (with regular dice). But for the interface it would result in ```choice(specialchar_list)``` and it would be impossible from the "plugins" point of view to make a difference here. Instead the source might had to ask for the number of dice available and could then determine the number of rolls to make for a certain length of words (wordlists) or chars (special chars).

From the purely mathematical point of view it should be possible to get enough dice rolls to get at least the entropy expected from the number of words/chars (plus maybe some extra-entropy being discarded). But that might conflict with the instructions given by Mr. Reinhold. Something I would like to avoid in the first place.

Overall I would tend to keep the entropy-per-word ratio at the expected level rather than discarding words/chars. But if that's a no-opt, issuing warnings would be okay as well, given that people are informed about what they get.

**Next Steps**

I am about to put the SystemRandom in a separate module we could use for all standard sources-of-randomness. This seems to work locally already, but I have to add tests and all that. I think I can finish that until tomorrow evening. If you want you could then add the "dice" source following the (very simple) pattern of SystemRandom. I think I will make use of setuptools entry_points to enable other Python packages to provide randomness-sources as well.

If that's okay, I would ping you after pushing the local stuff, most probably somewhen tomorrow.

**Configurable Defaults**

A great idea. Yes, I wold love to see them. That might be next step after random sources.

**Debian Packaging**

I love Debian and have not the slightest idea how to do the packaging correctly. What should I say? Awesome!

Thanks again for your input,

-- 
Uli

**Comment by ulif** [comment]
@drebs 

I think I could prepare the package now for the random-sources thing. If you like, please go ahead and add the 'dice' source. It could land in the new random_sources module and must be registered in setup.py to be collected by main(). I am sure you get it quickly when you look into the sources.

Please tell, if you want help.

Please also tell, how you want to be mentioned in the 'credits/contributors' section of README. Or simply add yourself as part of another PR.

Many thanks in advance,

-- 
Uli

**Comment by ulif** [comment]
@drebs I started a new branch real-dice-source for development of the new random source plugin.

If you want, you are very welcome to implement this in the new branch, maybe in a new PR (I hope that works with branches).

The branch yet contains a single test, but if you want I can add more.

I also thought again about the lower-entropy-problem with dice and came to the conclusion that your solution would probably be the best, i.e. we can tell the user that not all parts of the wordlist might be used, but we use at least log(N)/log(6) words if the wordlist contains N words. That would also mean, that a user would have to roll log(N)/log(6) dice at the same time or a single dice log(N)/log(6) times, right? Certainly a procedure coming close to the original paper/pen model.

If you run into trouble with the branch, please tell! I'd merge the branch then back into master. Your help would be appreciated very much.

Best regards,

-- 
Uli

**Comment by andrejb** [comment]
I'm closing this because we decided to continue the discussion on https://github.com/ulif/diceware/issues/5 and eventually open a new pull request.

**Comment by ulif** [comment]
Ok, I am closing this one now, while continuing the discussion on #5 . This means we *will* support real dice as source of randomness, we just have to discuss *how* this should work in detail.

Thanks to everybody,

-- 
Uli

**Pull request closed without merging**
