### PR TITLE
Include wordlist_en.txt via pip install (for real this time)

### LINKED ISSUE #1: Wordlists aren't included during installation
The default `wordlist_en.txt` is not included during installation via pip. Steps to reproduce:

```
vagrant@vagrant-ubuntu-trusty-64:~$ sudo aptitude install python-pip
vagrant@vagrant-ubuntu-trusty-64:~$ sudo pip install diceware
```
Then:
```
vagrant@vagrant-ubuntu-trusty-64:~$ diceware
Traceback (most recent call last):
  File "/usr/local/bin/diceware", line 9, in <module>
    load_entry_point('diceware==0.2', 'console_scripts', 'diceware')()
  File "/usr/local/lib/python2.7/dist-packages/diceware.py", line 137, in main
    fd=options.infile
  File "/usr/local/lib/python2.7/dist-packages/diceware.py", line 110, in get_passphrase
    fd = open(get_wordlist_path(lang), 'r')
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/wordlists/wordlist_en.txt'
```
This can be resolved via the `data_files` directive in `setup.py` ([docs](https://docs.python.org/2/distutils/setupscript.html#installing-additional-files)):

```
    data_files=[
        ('wordlists', ['wordlists/wordlist_en.txt']),
        ],
```

Doing so will ensure that `wordlist_en.txt` is accessible by the module. Pull request on its way. Added a few Travis checks as well.

### PR DESCRIPTION
**Pull request by conorsch**
OK, got it. Had to push the wordlist files out to two different locations, `site-packages` and `dist-packages`, in order to support Ubuntu. That's a kludge, but it works, and `pip uninstall diceware` removes files from both locations, which is good. I don't have the ability to test on a Mac, but this should work there, too.

Installing to both locations is really only necessary to support `pip install --user diceware` under Ubuntu, but I think it's worth doing. `sudo pip install diceware` also works fine.

All tests are passing. I recommend a minor version bump (e.g. 0.4.1) to make sure the wordlists are in place, then republishing to pip.

Resolves #1 (again).

### CODE REVIEW

**Comment by conorsch** [comment]
[Further reading on Ubuntu's handling](http://stackoverflow.com/a/1558028/140800) of `site-packages` and `dist-packages`.

**Comment by ulif** [comment]
I still got problems when creating an sdist egg (as provided by pypi) and trying to install that locally into a virtualenv:

    $ virtualenv py27
    $ source py27/bin/activate                 # activate virtualenv
    $ python setup.py sdist                      # create source distribution
    $ pip install --no-index \
                       --find-links=file:///path-to/dist/diceware-0.4.dev0.tar.gz \
                       diceware
    Ignoring indexes: https://pypi.python.org/simple
    Collecting diceware
    Installing collected packages: diceware
      Running setup.py install for diceware
        error: can't copy 'diceware-wordlists/wordlist_en.txt': doesn't exist or not a regular file

I think that is because `diceware-wordlists` is not listed in MANIFEST.in.

Apart from that I think that Ubuntu-specific code should be avoided if possible. Maybe like described in [setuptools docs](https://pythonhosted.org/setuptools/setuptools.html#accessing-data-files-at-runtime)

Or we do it the simple straight way and put everything inside a package.

**Comment by conorsch** [comment]
Ah, I see we're working on this at the same time! This patch definitely solves the problem:

```
diff --git a/MANIFEST.in b/MANIFEST.in
index 2552183..2e8548e 100644
--- a/MANIFEST.in
+++ b/MANIFEST.in
@@ -1,2 +1,2 @@
-recursive-include wordlists *.txt
+recursive-include diceware-wordlists *.txt
 include README.rst CHANGES.rst LICENSE
```
That's about as simple as it gets. But there are indeed benefits to restructuring the module to be more nested, but only if you plan to add more utils and such in the near future. My lazy installation method before was `pip install .`, which didn't catch the `MANIFEST.in` omission. Thanks for catching that!

Would love to see a saner implementation of supporting site-packages 'and' dist-packages. Will read more.

**Comment by ulif** [comment]
Oh, just spotted your message. Never tried `pip install .`. That's cool! Also tried the above change and got no errors any more. Anyway...

I just pushed the changes to turn the module into a package and hope you don't mind if your pull-request will not be pulled this time. After all I have a bad feeling about data files stored *somewhere*. (On the other hand it feels like The Right Thing to put static data in distribution-dependent locations)

For now,  many thanks for the feedback, high-standard pull-requests and uncovering that problem.

**Comment by conorsch** [comment]
New module structure works great, and it's more future-compatible, too. I'll keep an eye out for the new version published to pip!

**Comment by ulif** [comment]
Just released 0.3.1, which should at least give you less trouble. Thanks for your really valuable input! Please tell if you got any wishes or find new bugs!

-- Uli

**Pull request closed without merging**
