### PR TITLE
Add spanish word list

### PR DESCRIPTION
**Pull request by jawlenskys**
Add a 8192 words-long Spanish wordlist. The wordlist was generated from two different sources of words:

- The file `/usr/share/dict/spanish` from Debian's wspanish package.
- A list of the most used Spanish words from [Corpus de Referencia del Español Actual (CREA)](https://corpus.rae.es/lfrecuencias.html).

The final Spanish wordlist has been generated as follows:

    * Start from /usr/share/dict/spanish and filter out:
        - words not matching /^[a-z]+$/
        - words shorter than 4 characters
        - words longer than 8 characters
    * Do the same with the CREA word list.
    * Compare both lists and extract the words that appear in both lists.
    * Remove all words that are a suffix of any other word in the list.
    * Remove some offending and non-Spanish words.
    * Change some of the hard-to-remember words and replace them
      with some easy-to-remember words from CREA's list.

### CODE REVIEW

**Comment by ulif** [comment]
Hey Victor,
Impressive work! Thanks a lot!

/ulif

**Comment by jawlenskys** [comment]
Hi @ulif,
I've only just realised that I didn't specify the licence of the word lists I provided (es, ca and it). I'm fine with the CC-BY-3.0.

These three word lists were also provided as part of [Tails](https://tails.net). Should I create a PR to add this information?

**Comment by ulif** [comment]
Hi Victor,

Could you also imagine to apply CC BY 4.0 to your lists? It seems to be a bit easier to adapt for licensees (no need anymore to tell the title of a work, for instance) and looks more mature than the previous CC licenses. I will switch at least my own lists to CC BY 4.0. ([Differences](https://wiki.creativecommons.org/wiki/License_Versions#Detailed_attribution_comparison_chart))

Awesome, that your lists are also part of Tails. This info should be given also in the diceware docs. I love Tails, support it also financially, and try to spread it whenever possible :)

I am planning for a (major) release around chrismas, just waiting for a longer French wordlist from Tango. Therefore I would be happy to incorporate your copyrights (with a remark about Tails) in diceware, but also wouldn't refuse a PR if you have the time :)

**Comment by jawlenskys** [comment]
> Could you also imagine to apply CC BY 4.0 to your lists?

Yes, no problem.

> I am planning for a (major) release around chrismas, just waiting for a longer French wordlist from Tango. Therefore I would be happy to incorporate your copyrights (with a remark about Tails) in diceware, but also wouldn't refuse a PR if you have the time :)

That sounds great! Done in #113.

**Pull request merged**
