### PR TITLE
Remove the n.. word from worldlists

### PR DESCRIPTION
**Pull request by kmille**
The n.. word is discriminating. Please remove it from the wordlists.

### CODE REVIEW

**Comment by ulif** [comment]
Hi @kmille , Thanks for your hints.

While you're generally right, three things have to be thought over.

First, please do not remove terms from lists without (carefully) providing replacements. The length of wordlists determines their cryptographical strength. You should have noticed that actually, while running the tests with your changes.

Please run the tests before commiting PRs.

Ideally, replacements
- do not inject new prefix codes
- have the length of other terms in the list
- cannot easily be confused with other terms
- contain no special chars

Then, changing the `*-orig` lists cannot be done without removing them completely. That's because I am not the source of these lists and they are provided for reference. Instead, you should ask A G Reinhold to remove the n-word from the main source, which can be found here: https://theworld.com/%7Ereinhold/diceware.wordlist.asc

Third, the n-word is, best to my knowledge, not a racist word in Portuguese or Brazilian. I will talk to some native speakers about that. If you have other sources, I would be happy to learn.

Please tell, which of the first two tasks you are willing to take over.

**Comment by kmille** [comment]
Hey @ulif 
I really appreciate your constructive feedback! Please, give me some time to think about. I'm just doing too many small things (like this) that are exploding right now.

**Comment by ulif** [comment]
Hi @kmille ,
Good to know. I can care for the problem if you agree. Just did not want to exclude you from handlung "your" PR/Issue.
If you do not object, I would try to fix the issue myself. Generating proper wordlists automatically was on my todo list anyway :)

**Comment by kmille** [comment]
Feel free to handle this PR :)
Thanks for your effort!

**Comment by BrandonKMLee** [comment]
For future references, please check the list of repos that catalogs other curse words in  https://github.com/words/cuss/issues/40

**Comment by ulif** [comment]
Thank you, @BrandonKMLee , really helpful!
I am also looking for "bad-word" lists in German. Any hints are much apprecitated.

**Comment by BrandonKMLee** [comment]
- https://github.com/chucknorris-io/swear-words/blob/master/de
- https://github.com/thisandagain/washyourmouthoutwithsoap/blob/develop/data/build.json#L836

**Comment by ulif** [comment]
Very interesting! Thanks again, @BrandonKMLee ! 
It looks like lots of people work with relatively small blacklists, where they collect swear-words they have seen somewhere sometime ago :) More helpful might be wordlists based on sentiment analysis of large text corpora.
I found something like that for German words. Also quite interesting although it is still a short list and does not contain the typical swear-words: SentiWS - available at https://wortschatz.uni-leipzig.de/download/.

**Pull request closed without merging**
